import { useEffect, useMemo } from "react";
import { useQuery } from "@tanstack/react-query";
import { useParams, Link, useLocation } from "wouter";
import {
  ArrowLeft,
  FileText,
  User,
  Clock,
  Check,
  X,
  Lock,
  AlertCircle,
  MoreVertical,
  Printer,
  Download,
  Trash2,
  CheckCircle,
  XCircle,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
  TableFooter,
} from "@/components/ui/table";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import {
  Tooltip,
  TooltipContent,
  TooltipProvider,
  TooltipTrigger,
} from "@/components/ui/tooltip";
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from "@/components/ui/alert-dialog";
import { Skeleton } from "@/components/ui/skeleton";
import { Progress } from "@/components/ui/progress";
import { Separator } from "@/components/ui/separator";
import { useTenant } from "@/hooks/useTenant";
import { useToast } from "@/hooks/use-toast";
import { useAuth } from "@/hooks/useAuth";
import { formatCurrency } from "@/lib/currency-utils";
import type { Currency } from "@shared/schema";
import { useState } from "react";

type JournalEntryStatus = 'draft' | 'pending_approval' | 'approved' | 'posted' | 'rejected';
type SourceDocumentType = 'invoice' | 'bill' | 'payment' | 'customer_payment' | 'credit_note' | 'debit_note' | 'expense' | 'fixed_asset' | 'inventory_adjustment' | 'depreciation' | 'payment_batch' | 'approval';

interface UserInfo {
  id: string;
  firstName: string | null;
  lastName: string | null;
  email: string | null;
}

interface JournalEntryLeg {
  id: string;
  accountId: string;
  type: 'Debit' | 'Credit';
  amount: string;
  description: string | null;
  account?: {
    id: string;
    code: string;
    name: string;
  };
}

interface JournalEntry {
  id: string;
  tenantId: string;
  journalEntryNumber: string | null;
  entryDate: string;
  referenceNumber: string | null;
  description: string | null;
  notes: string | null;
  status: JournalEntryStatus;
  currencyCode: string;
  sourceDocumentType: SourceDocumentType | null;
  sourceDocumentId: string | null;
  isAutoGenerated: boolean | null;
  modificationLocked: boolean | null;
  workflowRequestId: string | null;
  preparedBy: string | null;
  preparedAt: string | null;
  postedBy: string | null;
  postedAt: string | null;
  preparedByUser?: UserInfo | null;
  postedByUser?: UserInfo | null;
  legs?: JournalEntryLeg[];
}

interface AuditTrailEvent {
  action: string;
  timestamp: string;
  user: UserInfo;
  comments?: string;
}

interface WorkflowStep {
  stepNumber: number;
  stepName: string;
  assignedApprovers: string[];
  status: 'pending' | 'approved' | 'rejected';
  approver?: string;
  actionTimestamp?: string;
  comments?: string;
}

interface WorkflowStatus {
  currentStep: number;
  totalSteps: number;
  steps: WorkflowStep[];
  isComplete: boolean;
  isRejected: boolean;
  rejectionReason?: string;
}

export default function JournalEntryDetailPage() {
  const { id } = useParams<{ id: string }>();
  const [, navigate] = useLocation();
  const { currentTenant } = useTenant();
  const { toast } = useToast();
  const { isAuthenticated, isLoading: authLoading } = useAuth();
  const [showDeleteDialog, setShowDeleteDialog] = useState(false);

  useEffect(() => {
    if (!authLoading && !isAuthenticated) {
      toast({
        title: "Unauthorized",
        description: "You are logged out. Logging in again...",
        variant: "destructive",
      });
      setTimeout(() => {
        window.location.href = "/api/login";
      }, 500);
    }
  }, [isAuthenticated, authLoading, toast]);

  // Fetch single journal entry by ID
  const { data: entry, isLoading: entriesLoading, error: entriesError } = useQuery<JournalEntry>({
    queryKey: ["/api/journal-entries", id, { tenantId: currentTenant?.id }],
    enabled: !!currentTenant?.id && !!id,
  });

  // Fetch audit trail (with tenant context for proper cache scoping)
  const { data: auditTrailResponse, isLoading: auditLoading } = useQuery<{ timeline: AuditTrailEvent[] }>({
    queryKey: ['/api/journal-entries', id, 'audit-trail', { tenantId: currentTenant?.id }],
    enabled: !!currentTenant?.id && !!id,
  });

  const auditTrail = auditTrailResponse?.timeline || [];

  // Fetch currencies
  const { data: currencies = [] } = useQuery<Currency[]>({
    queryKey: ["/api/currencies", currentTenant?.id],
    enabled: !!currentTenant?.id,
  });

  const formatDate = (date: string) => {
    return new Date(date).toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'short',
      day: 'numeric',
    });
  };

  const formatDateTime = (date: string) => {
    return new Date(date).toLocaleString('en-US', {
      year: 'numeric',
      month: 'short',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
    });
  };

  const getUserName = (user: UserInfo | null | undefined) => {
    if (!user) return "—";
    const firstName = user.firstName || "";
    const lastName = user.lastName || "";
    return `${firstName} ${lastName}`.trim() || user.email || "—";
  };

  const getStatusBadge = (status: JournalEntryStatus) => {
    const config: Record<JournalEntryStatus, { variant: "default" | "secondary" | "destructive" | "outline"; className?: string; label: string }> = {
      draft: { variant: "secondary", label: "Draft" },
      pending_approval: { variant: "outline", className: "bg-amber-100 text-amber-800 border-amber-300 dark:bg-amber-950 dark:text-amber-300 dark:border-amber-800", label: "Pending Approval" },
      approved: { variant: "outline", className: "bg-green-100 text-green-800 border-green-300 dark:bg-green-950 dark:text-green-300 dark:border-green-800", label: "Approved" },
      posted: { variant: "default", label: "Posted" },
      rejected: { variant: "destructive", label: "Rejected" },
    };
    const { variant, className, label } = config[status] || { variant: "secondary", label: status };
    return (
      <Badge variant={variant} className={className} data-testid={`badge-status-${status}`}>
        {label}
      </Badge>
    );
  };

  const getSourceDocumentLink = (type: SourceDocumentType | null, docId: string | null) => {
    if (!type || !docId) return null;
    
    const routes: Record<SourceDocumentType, string> = {
      invoice: `/invoices/${docId}`,
      bill: `/bills/${docId}`,
      payment: `/payments/${docId}`,
      customer_payment: `/customer-payments/${docId}`,
      credit_note: `/credit-notes/${docId}`,
      debit_note: `/debit-notes/${docId}`,
      expense: `/expenses/${docId}`,
      fixed_asset: `/assets/${docId}`,
      inventory_adjustment: `/inventory/${docId}`,
      depreciation: `/assets/${docId}`,
      payment_batch: `/payments/${docId}`,
      approval: `/approvals/${docId}`,
    };

    const labels: Record<SourceDocumentType, string> = {
      invoice: "Invoice",
      bill: "Bill",
      payment: "Vendor Payment",
      customer_payment: "Customer Payment",
      credit_note: "Credit Note",
      debit_note: "Debit Note",
      expense: "Expense",
      fixed_asset: "Fixed Asset",
      inventory_adjustment: "Inventory Adjustment",
      depreciation: "Depreciation",
      payment_batch: "Payment Batch",
      approval: "Approval",
    };

    return {
      path: routes[type],
      label: labels[type] || type,
    };
  };

  const calculateTotals = () => {
    if (!entry?.legs || entry.legs.length === 0) {
      return { totalDebits: 0, totalCredits: 0, isBalanced: true };
    }

    const totalDebits = entry.legs
      .filter(leg => leg.type === 'Debit')
      .reduce((sum, leg) => sum + parseFloat(leg.amount), 0);

    const totalCredits = entry.legs
      .filter(leg => leg.type === 'Credit')
      .reduce((sum, leg) => sum + parseFloat(leg.amount), 0);

    const isBalanced = Math.abs(totalDebits - totalCredits) < 0.01;

    return { totalDebits, totalCredits, isBalanced };
  };

  const handleDelete = () => {
    // Placeholder for delete functionality
    toast({
      title: "Delete functionality",
      description: "Delete API not implemented yet",
    });
    setShowDeleteDialog(false);
  };

  const handlePrint = () => {
    window.print();
  };

  const handleExportPDF = () => {
    toast({
      title: "Export PDF",
      description: "PDF export functionality coming soon",
    });
  };

  const isLoading = entriesLoading || authLoading;

  if (!currentTenant) {
    return (
      <div className="flex flex-col items-center justify-center h-[calc(100vh-4rem)] gap-4">
        <div className="text-center">
          <h2 className="text-2xl font-semibold mb-2">No Workspace Selected</h2>
          <p className="text-muted-foreground">Please select or create a workspace to continue</p>
        </div>
      </div>
    );
  }

  if (isLoading) {
    return (
      <div className="space-y-6">
        <div className="flex items-center gap-4">
          <Skeleton className="h-10 w-10" />
          <Skeleton className="h-8 w-64" />
        </div>
        <div className="grid gap-6 md:grid-cols-2">
          <Skeleton className="h-64" />
          <Skeleton className="h-64" />
        </div>
        <Skeleton className="h-96" />
      </div>
    );
  }

  if (entriesError || !entry) {
    return (
      <div className="flex flex-col items-center justify-center h-[calc(100vh-4rem)] gap-4">
        <AlertCircle className="h-12 w-12 text-destructive" />
        <div className="text-center">
          <h2 className="text-2xl font-semibold mb-2">Journal Entry Not Found</h2>
          <p className="text-muted-foreground mb-4">
            {entriesError instanceof Error ? entriesError.message : 'The requested journal entry could not be found'}
          </p>
          <Link href="/journal-entries">
            <Button data-testid="button-back-to-list">
              <ArrowLeft className="mr-2 h-4 w-4" />
              Back to Journal Entries
            </Button>
          </Link>
        </div>
      </div>
    );
  }

  const sourceLink = getSourceDocumentLink(entry.sourceDocumentType, entry.sourceDocumentId);
  const { totalDebits, totalCredits, isBalanced } = calculateTotals();

  return (
    <div className="space-y-6">
      {/* Header Section */}
      <div className="flex items-start justify-between gap-4 flex-wrap">
        <div className="flex-1 min-w-0">
          <div className="flex items-center gap-4 mb-2">
            <Link href="/journal-entries">
              <Button variant="ghost" size="sm" data-testid="button-back">
                <ArrowLeft className="h-4 w-4" />
              </Button>
            </Link>
            <h1 className="text-3xl font-semibold truncate" data-testid="text-entry-number">
              {entry.journalEntryNumber || 'Journal Entry'}
            </h1>
            {getStatusBadge(entry.status)}
          </div>
          <div className="flex items-center gap-4 flex-wrap text-sm text-muted-foreground ml-14">
            <div className="flex items-center gap-2" data-testid="text-entry-date">
              <Clock className="h-4 w-4" />
              {formatDate(entry.entryDate)}
            </div>
            {entry.description && (
              <div className="flex-1 min-w-0 truncate" data-testid="text-description">
                {entry.description}
              </div>
            )}
          </div>
          <div className="flex items-center gap-2 mt-2 ml-14 flex-wrap">
            {entry.isAutoGenerated && (
              <TooltipProvider>
                <Tooltip>
                  <TooltipTrigger asChild>
                    <Badge variant="outline" className="gap-1" data-testid="badge-auto-generated">
                      <Lock className="h-3 w-3" />
                      Auto-Generated
                    </Badge>
                  </TooltipTrigger>
                  <TooltipContent>
                    This entry was automatically created by the system
                  </TooltipContent>
                </Tooltip>
              </TooltipProvider>
            )}
            {entry.modificationLocked && (
              <TooltipProvider>
                <Tooltip>
                  <TooltipTrigger asChild>
                    <Badge variant="outline" className="gap-1" data-testid="badge-locked">
                      <Lock className="h-3 w-3" />
                      Locked
                    </Badge>
                  </TooltipTrigger>
                  <TooltipContent>
                    This entry cannot be modified because it is {entry.isAutoGenerated ? 'auto-generated' : 'locked'}
                  </TooltipContent>
                </Tooltip>
              </TooltipProvider>
            )}
          </div>
        </div>
        <DropdownMenu>
          <DropdownMenuTrigger asChild>
            <Button variant="outline" size="sm" data-testid="button-actions">
              <MoreVertical className="h-4 w-4" />
            </Button>
          </DropdownMenuTrigger>
          <DropdownMenuContent align="end">
            <DropdownMenuItem onClick={handlePrint} data-testid="menu-item-print">
              <Printer className="mr-2 h-4 w-4" />
              Print
            </DropdownMenuItem>
            <DropdownMenuItem onClick={handleExportPDF} data-testid="menu-item-export-pdf">
              <Download className="mr-2 h-4 w-4" />
              Export PDF
            </DropdownMenuItem>
            {entry.status === 'draft' && (
              <DropdownMenuItem
                onClick={() => setShowDeleteDialog(true)}
                className="text-destructive"
                data-testid="menu-item-delete"
              >
                <Trash2 className="mr-2 h-4 w-4" />
                Delete
              </DropdownMenuItem>
            )}
          </DropdownMenuContent>
        </DropdownMenu>
      </div>

      <div className="grid gap-6 md:grid-cols-2">
        {/* Source Document Card */}
        {sourceLink && (
          <Card data-testid="card-source-document">
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <FileText className="h-5 w-5" />
                Source Document
              </CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              <div>
                <p className="text-sm text-muted-foreground mb-1">Document Type</p>
                <p className="font-medium" data-testid="text-source-type">{sourceLink.label}</p>
              </div>
              <div>
                <Link href={sourceLink.path}>
                  <Button variant="outline" size="sm" data-testid="button-view-source">
                    <FileText className="mr-2 h-4 w-4" />
                    View Source Document
                  </Button>
                </Link>
              </div>
            </CardContent>
          </Card>
        )}

        {/* Journal Entry Details Card */}
        <Card data-testid="card-entry-details">
          <CardHeader>
            <CardTitle>Entry Details</CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <div>
              <p className="text-sm text-muted-foreground mb-1">Entry Date</p>
              <p className="font-medium" data-testid="text-detail-entry-date">{formatDate(entry.entryDate)}</p>
            </div>
            {entry.referenceNumber && (
              <div>
                <p className="text-sm text-muted-foreground mb-1">Reference Number</p>
                <p className="font-medium" data-testid="text-reference-number">{entry.referenceNumber}</p>
              </div>
            )}
            <Separator />
            {entry.preparedByUser && entry.preparedAt && (
              <div>
                <p className="text-sm text-muted-foreground mb-1">Prepared By</p>
                <p className="font-medium" data-testid="text-prepared-by">
                  {getUserName(entry.preparedByUser)}
                </p>
                <p className="text-sm text-muted-foreground" data-testid="text-prepared-at">
                  {formatDateTime(entry.preparedAt)}
                </p>
              </div>
            )}
            {entry.postedByUser && entry.postedAt && (
              <div>
                <p className="text-sm text-muted-foreground mb-1">Posted By</p>
                <p className="font-medium" data-testid="text-posted-by">
                  {getUserName(entry.postedByUser)}
                </p>
                <p className="text-sm text-muted-foreground" data-testid="text-posted-at">
                  {formatDateTime(entry.postedAt)}
                </p>
              </div>
            )}
            <Separator />
            <div>
              <p className="text-sm text-muted-foreground mb-1">Status</p>
              <div data-testid="badge-detail-status">{getStatusBadge(entry.status)}</div>
            </div>
            {entry.workflowRequestId && (
              <div>
                <p className="text-sm text-muted-foreground mb-1">Workflow Status</p>
                <p className="font-medium" data-testid="text-workflow-id">In Approval Workflow</p>
              </div>
            )}
          </CardContent>
        </Card>
      </div>

      {/* Debit/Credit Legs Table */}
      <Card data-testid="card-journal-legs">
        <CardHeader>
          <CardTitle>Journal Entry Legs</CardTitle>
        </CardHeader>
        <CardContent>
          {!entry.legs || entry.legs.length === 0 ? (
            <div className="flex flex-col items-center justify-center py-12 text-center">
              <AlertCircle className="h-12 w-12 text-muted-foreground mb-4" />
              <p className="text-lg font-medium mb-2">No legs found</p>
              <p className="text-sm text-muted-foreground">
                This journal entry has no debit or credit legs
              </p>
            </div>
          ) : (
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Account Code</TableHead>
                  <TableHead>Account Name</TableHead>
                  <TableHead>Description</TableHead>
                  <TableHead className="text-right">Debit Amount</TableHead>
                  <TableHead className="text-right">Credit Amount</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {entry.legs
                  .sort((a, b) => {
                    const codeA = a.account?.code || '';
                    const codeB = b.account?.code || '';
                    return codeA.localeCompare(codeB);
                  })
                  .map((leg) => (
                    <TableRow key={leg.id} data-testid={`row-leg-${leg.id}`}>
                      <TableCell className="font-mono" data-testid={`text-account-code-${leg.id}`}>
                        {leg.account?.code || '—'}
                      </TableCell>
                      <TableCell data-testid={`text-account-name-${leg.id}`}>
                        {leg.account ? (
                          <Link href={`/accounts/${leg.accountId}`}>
                            <span className="text-primary hover:underline cursor-pointer">
                              {leg.account.name}
                            </span>
                          </Link>
                        ) : (
                          '—'
                        )}
                      </TableCell>
                      <TableCell data-testid={`text-leg-description-${leg.id}`}>
                        {leg.description || '—'}
                      </TableCell>
                      <TableCell className="text-right font-mono font-medium" data-testid={`text-debit-${leg.id}`}>
                        {leg.type === 'Debit' 
                          ? formatCurrency(parseFloat(leg.amount), entry.currencyCode, currencies)
                          : '—'
                        }
                      </TableCell>
                      <TableCell className="text-right font-mono font-medium" data-testid={`text-credit-${leg.id}`}>
                        {leg.type === 'Credit'
                          ? formatCurrency(parseFloat(leg.amount), entry.currencyCode, currencies)
                          : '—'
                        }
                      </TableCell>
                    </TableRow>
                  ))}
              </TableBody>
              <TableFooter>
                <TableRow>
                  <TableCell colSpan={3} className="font-semibold">Total</TableCell>
                  <TableCell className="text-right font-mono font-semibold" data-testid="text-total-debits">
                    {formatCurrency(totalDebits, entry.currencyCode, currencies)}
                  </TableCell>
                  <TableCell className="text-right font-mono font-semibold" data-testid="text-total-credits">
                    {formatCurrency(totalCredits, entry.currencyCode, currencies)}
                  </TableCell>
                </TableRow>
                <TableRow>
                  <TableCell colSpan={5} className="text-center">
                    {isBalanced ? (
                      <div className="flex items-center justify-center gap-2 text-green-600 dark:text-green-400" data-testid="text-balanced">
                        <CheckCircle className="h-4 w-4" />
                        <span className="font-medium">Balanced</span>
                      </div>
                    ) : (
                      <div className="flex items-center justify-center gap-2 text-destructive" data-testid="text-unbalanced">
                        <XCircle className="h-4 w-4" />
                        <span className="font-medium">
                          Unbalanced (Difference: {formatCurrency(Math.abs(totalDebits - totalCredits), entry.currencyCode, currencies)})
                        </span>
                      </div>
                    )}
                  </TableCell>
                </TableRow>
              </TableFooter>
            </Table>
          )}
        </CardContent>
      </Card>

      {/* Audit Trail Timeline */}
      {auditTrail.length > 0 && (
        <Card data-testid="card-audit-trail">
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <Clock className="h-5 w-5" />
              Audit Trail
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="space-y-6">
              {auditTrail.map((event, index) => (
                <div key={index} className="flex gap-4" data-testid={`audit-event-${index}`}>
                  <div className="flex flex-col items-center">
                    <div className="rounded-full bg-primary p-2">
                      {event.action.toLowerCase().includes('approve') ? (
                        <Check className="h-4 w-4 text-primary-foreground" />
                      ) : event.action.toLowerCase().includes('reject') ? (
                        <X className="h-4 w-4 text-primary-foreground" />
                      ) : (
                        <User className="h-4 w-4 text-primary-foreground" />
                      )}
                    </div>
                    {index < auditTrail.length - 1 && (
                      <div className="h-full w-0.5 bg-border mt-2 flex-1" />
                    )}
                  </div>
                  <div className="flex-1 pb-6">
                    <p className="font-medium" data-testid={`audit-action-${index}`}>
                      {event.action}
                    </p>
                    <p className="text-sm text-muted-foreground" data-testid={`audit-user-${index}`}>
                      {getUserName(event.user)} • {formatDateTime(event.timestamp)}
                    </p>
                    {event.comments && (
                      <p className="text-sm mt-1" data-testid={`audit-comments-${index}`}>
                        {event.comments}
                      </p>
                    )}
                  </div>
                </div>
              ))}
            </div>
          </CardContent>
        </Card>
      )}

      {/* Notes Section */}
      {entry.notes && (
        <Card data-testid="card-notes">
          <CardHeader>
            <CardTitle>Notes</CardTitle>
          </CardHeader>
          <CardContent>
            <p className="text-sm whitespace-pre-wrap" data-testid="text-notes">{entry.notes}</p>
          </CardContent>
        </Card>
      )}

      {/* Delete Confirmation Dialog */}
      <AlertDialog open={showDeleteDialog} onOpenChange={setShowDeleteDialog}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>Delete Journal Entry</AlertDialogTitle>
            <AlertDialogDescription>
              Are you sure you want to delete this journal entry? This action cannot be undone.
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel data-testid="button-cancel-delete">Cancel</AlertDialogCancel>
            <AlertDialogAction
              onClick={handleDelete}
              className="bg-destructive text-destructive-foreground hover:bg-destructive/90"
              data-testid="button-confirm-delete"
            >
              Delete
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
    </div>
  );
}
