import { useEffect, useMemo } from "react";
import { useQuery, useMutation } from "@tanstack/react-query";
import { useParams, Link, useLocation } from "wouter";
import {
  ArrowLeft,
  FileText,
  User,
  Clock,
  Check,
  X,
  Lock,
  AlertCircle,
  MoreVertical,
  Printer,
  Download,
  Trash2,
  CheckCircle,
  XCircle,
  UserCheck,
} from "lucide-react";
import { Button } from "@/shared/components/ui/button";
import { Badge } from "@/shared/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/shared/components/ui/card";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
  TableFooter,
} from "@/shared/components/ui/table";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "@/shared/components/ui/dropdown-menu";
import {
  Tooltip,
  TooltipContent,
  TooltipProvider,
  TooltipTrigger,
} from "@/shared/components/ui/tooltip";
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from "@/shared/components/ui/alert-dialog";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/shared/components/ui/dialog";
import { Skeleton } from "@/shared/components/ui/skeleton";
import { Progress } from "@/shared/components/ui/progress";
import { Separator } from "@/shared/components/ui/separator";
import { Textarea } from "@/shared/components/ui/textarea";
import { Label } from "@/shared/components/ui/label";
import { useTenant } from "@/shared/hooks/useTenant";
import { useToast } from "@/shared/hooks/use-toast";
import { useAuth } from "@/shared/hooks/useAuth";
import { formatCurrency } from "@/shared/lib/utils/currency-utils";
import { apiRequest, queryClient } from "@/shared/lib/api/queryClient";
import type { Currency } from "@shared/schema";
import { useState } from "react";

type JournalEntryStatus = 'draft' | 'pending_approval' | 'approved' | 'posted' | 'rejected';
type SourceDocumentType = 'invoice' | 'bill' | 'payment' | 'customer_payment' | 'credit_note' | 'debit_note' | 'expense' | 'fixed_asset' | 'inventory_adjustment' | 'depreciation' | 'payment_batch' | 'approval';

interface UserInfo {
  id: string;
  firstName: string | null;
  lastName: string | null;
  email: string | null;
}

interface JournalEntryLeg {
  id: string;
  accountId: string;
  type: 'Debit' | 'Credit';
  amount: string;
  description: string | null;
  account?: {
    id: string;
    code: string;
    name: string;
  };
}

interface JournalEntry {
  id: string;
  tenantId: string;
  journalEntryNumber: string | null;
  entryDate: string;
  referenceNumber: string | null;
  description: string | null;
  notes: string | null;
  status: JournalEntryStatus;
  currencyCode: string;
  sourceDocumentType: SourceDocumentType | null;
  sourceDocumentId: string | null;
  isAutoGenerated: boolean | null;
  modificationLocked: boolean | null;
  workflowRequestId: string | null;
  preparedBy: string | null;
  preparedAt: string | null;
  postedBy: string | null;
  postedAt: string | null;
  preparedByUser?: UserInfo | null;
  postedByUser?: UserInfo | null;
  legs?: JournalEntryLeg[];
}

interface AuditTrailEvent {
  action: string;
  timestamp: string;
  user: UserInfo;
  comments?: string;
}

interface ApprovalRequest {
  id: string;
  status: 'pending' | 'approved' | 'rejected';
  currentStep: number;
  workflowId: string;
  requestedBy: string;
  createdAt: string;
  assignedApprovers: string[];
}

interface ApprovalHistoryRecord {
  id: string;
  approvalRequestId: string;
  stepOrder: number;
  approverUserId: string;
  decision: 'approved' | 'rejected';
  comments: string | null;
  timestamp: string;
  createdAt: string;
  approver: UserInfo | null;
}

interface WorkflowStep {
  id: string;
  workflowId: string;
  stepOrder: number;
  stepName: string;
  assignedApprovers: string[];
  isParallel: boolean;
}

interface AuditTrailResponse {
  timeline: AuditTrailEvent[];
  approvalRequest: ApprovalRequest | null;
  approvalHistoryRecords: ApprovalHistoryRecord[];
  workflowSteps: WorkflowStep[];
}

export default function JournalEntryDetailPage() {
  const { id } = useParams<{ id: string }>();
  const [, navigate] = useLocation();
  const { currentTenant } = useTenant();
  const { toast } = useToast();
  const { user, isAuthenticated, isLoading: authLoading } = useAuth();
  const [showDeleteDialog, setShowDeleteDialog] = useState(false);
  const [showApproveDialog, setShowApproveDialog] = useState(false);
  const [showRejectDialog, setShowRejectDialog] = useState(false);
  const [approveComments, setApproveComments] = useState("");
  const [rejectReason, setRejectReason] = useState("");

  useEffect(() => {
    if (!authLoading && !isAuthenticated) {
      toast({
        title: "Unauthorized",
        description: "You are logged out. Logging in again...",
        variant: "destructive",
      });
      setTimeout(() => {
        window.location.href = "/api/login";
      }, 500);
    }
  }, [isAuthenticated, authLoading, toast]);

  // Fetch single journal entry by ID
  const { data: entry, isLoading: entriesLoading, error: entriesError } = useQuery<JournalEntry>({
    queryKey: ["/api/journal-entries", id, { tenantId: currentTenant?.id }],
    enabled: !!currentTenant?.id && !!id,
  });

  // Fetch audit trail (with tenant context for proper cache scoping)
  const { data: auditTrailResponse, isLoading: auditLoading } = useQuery<AuditTrailResponse>({
    queryKey: ['/api/journal-entries', id, 'audit-trail', { tenantId: currentTenant?.id }],
    enabled: !!currentTenant?.id && !!id,
  });

  const auditTrail = auditTrailResponse?.timeline || [];
  const approvalRequest = auditTrailResponse?.approvalRequest;
  const approvalHistoryRecords = auditTrailResponse?.approvalHistoryRecords || [];
  const workflowSteps = auditTrailResponse?.workflowSteps || [];

  // Fetch currencies
  const { data: currencies = [] } = useQuery<Currency[]>({
    queryKey: ["/api/currencies", currentTenant?.id],
    enabled: !!currentTenant?.id,
  });

  // Approve mutation
  const approveMutation = useMutation({
    mutationFn: async (comments?: string) => {
      if (!currentTenant?.id) {
        throw new Error("No tenant selected");
      }
      return apiRequest(`/api/journal-entries/${id}/approve`, {
        method: "POST",
        headers: { 
          "Content-Type": "application/json",
          "x-tenant-id": currentTenant.id 
        },
        body: JSON.stringify({ comments }),
      });
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["/api/journal-entries", id, { tenantId: currentTenant?.id }] });
      queryClient.invalidateQueries({ queryKey: ['/api/journal-entries', id, 'audit-trail', { tenantId: currentTenant?.id }] });
      queryClient.invalidateQueries({ queryKey: ["/api/journal-entries", { tenantId: currentTenant?.id }] });
      toast({
        title: "Approved",
        description: "Journal entry has been approved successfully",
      });
      setShowApproveDialog(false);
      setApproveComments("");
    },
    onError: (error: any) => {
      toast({
        title: "Approval failed",
        description: error.message || "Failed to approve journal entry",
        variant: "destructive",
      });
    },
  });

  // Reject mutation
  const rejectMutation = useMutation({
    mutationFn: async (rejectionReason: string) => {
      if (!currentTenant?.id) {
        throw new Error("No tenant selected");
      }
      return apiRequest(`/api/journal-entries/${id}/reject`, {
        method: "POST",
        headers: { 
          "Content-Type": "application/json",
          "x-tenant-id": currentTenant.id 
        },
        body: JSON.stringify({ rejectionReason }),
      });
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["/api/journal-entries", id, { tenantId: currentTenant?.id }] });
      queryClient.invalidateQueries({ queryKey: ['/api/journal-entries', id, 'audit-trail', { tenantId: currentTenant?.id }] });
      queryClient.invalidateQueries({ queryKey: ["/api/journal-entries", { tenantId: currentTenant?.id }] });
      toast({
        title: "Rejected",
        description: "Journal entry has been rejected",
      });
      setShowRejectDialog(false);
      setRejectReason("");
    },
    onError: (error: any) => {
      toast({
        title: "Rejection failed",
        description: error.message || "Failed to reject journal entry",
        variant: "destructive",
      });
    },
  });

  const handleApprove = () => {
    approveMutation.mutate(approveComments || undefined);
  };

  const handleReject = () => {
    if (!rejectReason.trim()) {
      toast({
        title: "Rejection reason required",
        description: "Please provide a reason for rejection",
        variant: "destructive",
      });
      return;
    }
    rejectMutation.mutate(rejectReason);
  };

  // Check if current user can approve current step
  const canApproveCurrentStep = useMemo(() => {
    if (!user || !approvalRequest || !workflowSteps.length) return false;
    if (entry?.status !== 'pending_approval') return false;
    
    const currentStep = workflowSteps.find(s => s.stepOrder === approvalRequest.currentStep);
    if (!currentStep) return false;
    
    return currentStep.assignedApprovers.includes(user.id);
  }, [user, approvalRequest, workflowSteps, entry?.status]);

  const formatDate = (date: string) => {
    return new Date(date).toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'short',
      day: 'numeric',
    });
  };

  const formatDateTime = (date: string) => {
    return new Date(date).toLocaleString('en-US', {
      year: 'numeric',
      month: 'short',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
    });
  };

  const getUserName = (user: UserInfo | null | undefined) => {
    if (!user) return "—";
    const firstName = user.firstName || "";
    const lastName = user.lastName || "";
    return `${firstName} ${lastName}`.trim() || user.email || "—";
  };

  const getStatusBadge = (status: JournalEntryStatus) => {
    const config: Record<JournalEntryStatus, { variant: "default" | "secondary" | "destructive" | "outline"; className?: string; label: string }> = {
      draft: { variant: "secondary", label: "Draft" },
      pending_approval: { variant: "outline", className: "bg-amber-100 text-amber-800 border-amber-300 dark:bg-amber-950 dark:text-amber-300 dark:border-amber-800", label: "Pending Approval" },
      approved: { variant: "outline", className: "bg-green-100 text-green-800 border-green-300 dark:bg-green-950 dark:text-green-300 dark:border-green-800", label: "Approved" },
      posted: { variant: "default", label: "Posted" },
      rejected: { variant: "destructive", label: "Rejected" },
    };
    const { variant, className, label } = config[status] || { variant: "secondary", label: status };
    return (
      <Badge variant={variant} className={className} data-testid={`badge-status-${status}`}>
        {label}
      </Badge>
    );
  };

  const getSourceDocumentLink = (type: SourceDocumentType | null, docId: string | null) => {
    if (!type || !docId) return null;
    
    const routes: Record<SourceDocumentType, string> = {
      invoice: `/invoices/${docId}`,
      bill: `/bills/${docId}`,
      payment: `/payments/${docId}`,
      customer_payment: `/customer-payments/${docId}`,
      credit_note: `/credit-notes/${docId}`,
      debit_note: `/debit-notes/${docId}`,
      expense: `/expenses/${docId}`,
      fixed_asset: `/assets/${docId}`,
      inventory_adjustment: `/inventory/${docId}`,
      depreciation: `/assets/${docId}`,
      payment_batch: `/payments/${docId}`,
      approval: `/approvals/${docId}`,
    };

    const labels: Record<SourceDocumentType, string> = {
      invoice: "Invoice",
      bill: "Bill",
      payment: "Vendor Payment",
      customer_payment: "Customer Payment",
      credit_note: "Credit Note",
      debit_note: "Debit Note",
      expense: "Expense",
      fixed_asset: "Fixed Asset",
      inventory_adjustment: "Inventory Adjustment",
      depreciation: "Depreciation",
      payment_batch: "Payment Batch",
      approval: "Approval",
    };

    return {
      path: routes[type],
      label: labels[type] || type,
    };
  };

  const calculateTotals = () => {
    if (!entry?.legs || entry.legs.length === 0) {
      return { totalDebits: 0, totalCredits: 0, isBalanced: true };
    }

    const totalDebits = entry.legs
      .filter(leg => leg.type === 'Debit')
      .reduce((sum, leg) => sum + parseFloat(leg.amount), 0);

    const totalCredits = entry.legs
      .filter(leg => leg.type === 'Credit')
      .reduce((sum, leg) => sum + parseFloat(leg.amount), 0);

    const isBalanced = Math.abs(totalDebits - totalCredits) < 0.01;

    return { totalDebits, totalCredits, isBalanced };
  };

  const handleDelete = () => {
    // Placeholder for delete functionality
    toast({
      title: "Delete functionality",
      description: "Delete API not implemented yet",
    });
    setShowDeleteDialog(false);
  };

  const handlePrint = () => {
    window.print();
  };

  const handleExportPDF = () => {
    toast({
      title: "Export PDF",
      description: "PDF export functionality coming soon",
    });
  };

  const isLoading = entriesLoading || authLoading;

  if (!currentTenant) {
    return (
      <div className="flex flex-col items-center justify-center h-[calc(100vh-4rem)] gap-4">
        <div className="text-center">
          <h2 className="text-2xl font-semibold mb-2">No Workspace Selected</h2>
          <p className="text-muted-foreground">Please select or create a workspace to continue</p>
        </div>
      </div>
    );
  }

  if (isLoading) {
    return (
      <div className="space-y-6">
        <div className="flex items-center gap-4">
          <Skeleton className="h-10 w-10" />
          <Skeleton className="h-8 w-64" />
        </div>
        <div className="grid gap-6 md:grid-cols-2">
          <Skeleton className="h-64" />
          <Skeleton className="h-64" />
        </div>
        <Skeleton className="h-96" />
      </div>
    );
  }

  if (entriesError || !entry) {
    return (
      <div className="flex flex-col items-center justify-center h-[calc(100vh-4rem)] gap-4">
        <AlertCircle className="h-12 w-12 text-destructive" />
        <div className="text-center">
          <h2 className="text-2xl font-semibold mb-2">Journal Entry Not Found</h2>
          <p className="text-muted-foreground mb-4">
            {entriesError instanceof Error ? entriesError.message : 'The requested journal entry could not be found'}
          </p>
          <Link href="/journal-entries">
            <Button data-testid="button-back-to-list">
              <ArrowLeft className="mr-2 h-4 w-4" />
              Back to Journal Entries
            </Button>
          </Link>
        </div>
      </div>
    );
  }

  const sourceLink = getSourceDocumentLink(entry.sourceDocumentType, entry.sourceDocumentId);
  const { totalDebits, totalCredits, isBalanced } = calculateTotals();

  return (
    <div className="space-y-6">
      {/* Header Section */}
      <div className="flex items-start justify-between gap-4 flex-wrap">
        <div className="flex-1 min-w-0">
          <div className="flex items-center gap-4 mb-2">
            <Link href="/journal-entries">
              <Button variant="ghost" size="sm" data-testid="button-back">
                <ArrowLeft className="h-4 w-4" />
              </Button>
            </Link>
            <h1 className="text-3xl font-semibold truncate" data-testid="text-entry-number">
              {entry.journalEntryNumber || 'Journal Entry'}
            </h1>
            {getStatusBadge(entry.status)}
          </div>
          <div className="flex items-center gap-4 flex-wrap text-sm text-muted-foreground ml-14">
            <div className="flex items-center gap-2" data-testid="text-entry-date">
              <Clock className="h-4 w-4" />
              {formatDate(entry.entryDate)}
            </div>
            {entry.description && (
              <div className="flex-1 min-w-0 truncate" data-testid="text-description">
                {entry.description}
              </div>
            )}
          </div>
          <div className="flex items-center gap-2 mt-2 ml-14 flex-wrap">
            {entry.isAutoGenerated && (
              <TooltipProvider>
                <Tooltip>
                  <TooltipTrigger asChild>
                    <Badge variant="outline" className="gap-1" data-testid="badge-auto-generated">
                      <Lock className="h-3 w-3" />
                      Auto-Generated
                    </Badge>
                  </TooltipTrigger>
                  <TooltipContent>
                    This entry was automatically created by the system
                  </TooltipContent>
                </Tooltip>
              </TooltipProvider>
            )}
            {entry.modificationLocked && (
              <TooltipProvider>
                <Tooltip>
                  <TooltipTrigger asChild>
                    <Badge variant="outline" className="gap-1" data-testid="badge-locked">
                      <Lock className="h-3 w-3" />
                      Locked
                    </Badge>
                  </TooltipTrigger>
                  <TooltipContent>
                    This entry cannot be modified because it is {entry.isAutoGenerated ? 'auto-generated' : 'locked'}
                  </TooltipContent>
                </Tooltip>
              </TooltipProvider>
            )}
          </div>
        </div>
        <DropdownMenu>
          <DropdownMenuTrigger asChild>
            <Button variant="outline" size="sm" data-testid="button-actions">
              <MoreVertical className="h-4 w-4" />
            </Button>
          </DropdownMenuTrigger>
          <DropdownMenuContent align="end">
            <DropdownMenuItem onClick={handlePrint} data-testid="menu-item-print">
              <Printer className="mr-2 h-4 w-4" />
              Print
            </DropdownMenuItem>
            <DropdownMenuItem onClick={handleExportPDF} data-testid="menu-item-export-pdf">
              <Download className="mr-2 h-4 w-4" />
              Export PDF
            </DropdownMenuItem>
            {entry.status === 'draft' && (
              <DropdownMenuItem
                onClick={() => setShowDeleteDialog(true)}
                className="text-destructive"
                data-testid="menu-item-delete"
              >
                <Trash2 className="mr-2 h-4 w-4" />
                Delete
              </DropdownMenuItem>
            )}
          </DropdownMenuContent>
        </DropdownMenu>
      </div>

      <div className="grid gap-6 md:grid-cols-2">
        {/* Source Document Card */}
        {sourceLink && (
          <Card data-testid="card-source-document">
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <FileText className="h-5 w-5" />
                Source Document
              </CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              <div>
                <p className="text-sm text-muted-foreground mb-1">Document Type</p>
                <p className="font-medium" data-testid="text-source-type">{sourceLink.label}</p>
              </div>
              <div>
                <Link href={sourceLink.path}>
                  <Button variant="outline" size="sm" data-testid="button-view-source">
                    <FileText className="mr-2 h-4 w-4" />
                    View Source Document
                  </Button>
                </Link>
              </div>
            </CardContent>
          </Card>
        )}

        {/* Journal Entry Details Card */}
        <Card data-testid="card-entry-details">
          <CardHeader>
            <CardTitle>Entry Details</CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <div>
              <p className="text-sm text-muted-foreground mb-1">Entry Date</p>
              <p className="font-medium" data-testid="text-detail-entry-date">{formatDate(entry.entryDate)}</p>
            </div>
            {entry.referenceNumber && (
              <div>
                <p className="text-sm text-muted-foreground mb-1">Reference Number</p>
                <p className="font-medium" data-testid="text-reference-number">{entry.referenceNumber}</p>
              </div>
            )}
            <Separator />
            {entry.preparedByUser && entry.preparedAt && (
              <div>
                <p className="text-sm text-muted-foreground mb-1">Prepared By</p>
                <p className="font-medium" data-testid="text-prepared-by">
                  {getUserName(entry.preparedByUser)}
                </p>
                <p className="text-sm text-muted-foreground" data-testid="text-prepared-at">
                  {formatDateTime(entry.preparedAt)}
                </p>
              </div>
            )}
            {entry.postedByUser && entry.postedAt && (
              <div>
                <p className="text-sm text-muted-foreground mb-1">Posted By</p>
                <p className="font-medium" data-testid="text-posted-by">
                  {getUserName(entry.postedByUser)}
                </p>
                <p className="text-sm text-muted-foreground" data-testid="text-posted-at">
                  {formatDateTime(entry.postedAt)}
                </p>
              </div>
            )}
            <Separator />
            <div>
              <p className="text-sm text-muted-foreground mb-1">Status</p>
              <div data-testid="badge-detail-status">{getStatusBadge(entry.status)}</div>
            </div>
            {entry.workflowRequestId && (
              <div>
                <p className="text-sm text-muted-foreground mb-1">Workflow Status</p>
                <p className="font-medium" data-testid="text-workflow-id">In Approval Workflow</p>
              </div>
            )}
          </CardContent>
        </Card>
      </div>

      {/* Approval Panel */}
      {entry.workflowRequestId && entry.status === 'pending_approval' && approvalRequest && (
        <Card data-testid="card-approval-panel">
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <UserCheck className="h-5 w-5" />
              Approval Workflow
            </CardTitle>
          </CardHeader>
          <CardContent className="space-y-6">
            {/* Current Step Indicator */}
            <div>
              <div className="flex items-center gap-2 mb-2">
                <Badge variant="outline" data-testid="badge-current-step">
                  Step {approvalRequest.currentStep} of {workflowSteps.length || 1}
                </Badge>
                {approvalRequest.status === 'pending' && (
                  <Badge variant="outline" className="bg-amber-100 text-amber-800 border-amber-300 dark:bg-amber-950 dark:text-amber-300 dark:border-amber-800">
                    Pending
                  </Badge>
                )}
              </div>
              <Progress 
                value={workflowSteps.length > 0 ? (approvalRequest.currentStep / workflowSteps.length) * 100 : 0} 
                className="h-2" 
                data-testid="progress-workflow"
              />
            </div>

            {/* Current Step Approvers */}
            {(() => {
              const currentStep = workflowSteps.find(s => s.stepOrder === approvalRequest.currentStep);
              if (!currentStep) return null;
              
              return (
                <div>
                  <h3 className="text-sm font-semibold mb-3">Current Step: {currentStep.stepName || `Step ${approvalRequest.currentStep}`}</h3>
                  <div className="space-y-2">
                    <p className="text-sm text-muted-foreground">Assigned Approvers:</p>
                    <div className="flex flex-wrap gap-2">
                      {currentStep.assignedApprovers && currentStep.assignedApprovers.length > 0 ? (
                        currentStep.assignedApprovers.map((approverId, idx) => (
                          <Badge key={idx} variant="secondary" data-testid={`badge-approver-${idx}`}>
                            {approverId}
                          </Badge>
                        ))
                      ) : (
                        <p className="text-sm text-muted-foreground">No approvers assigned</p>
                      )}
                    </div>
                  </div>
                </div>
              );
            })()}

            {/* Approval History */}
            {approvalHistoryRecords.length > 0 && (
              <div>
                <Separator className="mb-4" />
                <h3 className="text-sm font-semibold mb-3">Approval History</h3>
                <div className="space-y-3">
                  {approvalHistoryRecords.map((record, idx) => (
                    <div 
                      key={record.id} 
                      className="flex items-start gap-3 p-3 rounded-lg bg-muted/50"
                      data-testid={`approval-history-${idx}`}
                    >
                      <div className="mt-0.5">
                        {record.decision === 'approved' ? (
                          <div className="rounded-full bg-green-100 dark:bg-green-950 p-1.5">
                            <CheckCircle className="h-4 w-4 text-green-600 dark:text-green-400" />
                          </div>
                        ) : (
                          <div className="rounded-full bg-destructive/10 p-1.5">
                            <XCircle className="h-4 w-4 text-destructive" />
                          </div>
                        )}
                      </div>
                      <div className="flex-1 min-w-0">
                        <div className="flex items-center gap-2 flex-wrap mb-1">
                          <Badge 
                            variant="outline" 
                            className={record.decision === 'approved' 
                              ? "bg-green-100 text-green-800 border-green-300 dark:bg-green-950 dark:text-green-300 dark:border-green-800"
                              : "bg-destructive/10 text-destructive border-destructive/20"
                            }
                            data-testid={`badge-decision-${idx}`}
                          >
                            {record.decision === 'approved' ? 'Approved' : 'Rejected'}
                          </Badge>
                          <span className="text-sm text-muted-foreground">
                            Step {record.stepOrder}
                          </span>
                        </div>
                        <p className="text-sm font-medium" data-testid={`text-approver-${idx}`}>
                          {getUserName(record.approver)}
                        </p>
                        <p className="text-xs text-muted-foreground" data-testid={`text-timestamp-${idx}`}>
                          {formatDateTime(record.timestamp)}
                        </p>
                        {record.comments && (
                          <p className="text-sm mt-2 p-2 rounded bg-background" data-testid={`text-comments-${idx}`}>
                            {record.comments}
                          </p>
                        )}
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            )}

            {/* Action Buttons */}
            {canApproveCurrentStep && (
              <>
                <Separator />
                <div className="flex gap-3">
                  <Button
                    onClick={() => setShowApproveDialog(true)}
                    disabled={approveMutation.isPending || rejectMutation.isPending}
                    className="flex-1"
                    data-testid="button-approve"
                  >
                    {approveMutation.isPending ? (
                      <>Processing...</>
                    ) : (
                      <>
                        <CheckCircle className="mr-2 h-4 w-4" />
                        Approve
                      </>
                    )}
                  </Button>
                  <Button
                    variant="destructive"
                    onClick={() => setShowRejectDialog(true)}
                    disabled={approveMutation.isPending || rejectMutation.isPending}
                    className="flex-1"
                    data-testid="button-reject"
                  >
                    {rejectMutation.isPending ? (
                      <>Processing...</>
                    ) : (
                      <>
                        <XCircle className="mr-2 h-4 w-4" />
                        Reject
                      </>
                    )}
                  </Button>
                </div>
              </>
            )}
          </CardContent>
        </Card>
      )}

      {/* Debit/Credit Legs Table */}
      <Card data-testid="card-journal-legs">
        <CardHeader>
          <CardTitle>Journal Entry Legs</CardTitle>
        </CardHeader>
        <CardContent>
          {!entry.legs || entry.legs.length === 0 ? (
            <div className="flex flex-col items-center justify-center py-12 text-center">
              <AlertCircle className="h-12 w-12 text-muted-foreground mb-4" />
              <p className="text-lg font-medium mb-2">No legs found</p>
              <p className="text-sm text-muted-foreground">
                This journal entry has no debit or credit legs
              </p>
            </div>
          ) : (
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Account Code</TableHead>
                  <TableHead>Account Name</TableHead>
                  <TableHead>Description</TableHead>
                  <TableHead className="text-right">Debit Amount</TableHead>
                  <TableHead className="text-right">Credit Amount</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {entry.legs
                  .sort((a, b) => {
                    const codeA = a.account?.code || '';
                    const codeB = b.account?.code || '';
                    return codeA.localeCompare(codeB);
                  })
                  .map((leg) => (
                    <TableRow key={leg.id} data-testid={`row-leg-${leg.id}`}>
                      <TableCell className="font-mono" data-testid={`text-account-code-${leg.id}`}>
                        {leg.account?.code || '—'}
                      </TableCell>
                      <TableCell data-testid={`text-account-name-${leg.id}`}>
                        {leg.account ? (
                          <Link href={`/accounts/${leg.accountId}`}>
                            <span className="text-primary hover:underline cursor-pointer">
                              {leg.account.name}
                            </span>
                          </Link>
                        ) : (
                          '—'
                        )}
                      </TableCell>
                      <TableCell data-testid={`text-leg-description-${leg.id}`}>
                        {leg.description || '—'}
                      </TableCell>
                      <TableCell className="text-right font-mono font-medium" data-testid={`text-debit-${leg.id}`}>
                        {leg.type === 'Debit' 
                          ? formatCurrency(parseFloat(leg.amount), entry.currencyCode, currencies)
                          : '—'
                        }
                      </TableCell>
                      <TableCell className="text-right font-mono font-medium" data-testid={`text-credit-${leg.id}`}>
                        {leg.type === 'Credit'
                          ? formatCurrency(parseFloat(leg.amount), entry.currencyCode, currencies)
                          : '—'
                        }
                      </TableCell>
                    </TableRow>
                  ))}
              </TableBody>
              <TableFooter>
                <TableRow>
                  <TableCell colSpan={3} className="font-semibold">Total</TableCell>
                  <TableCell className="text-right font-mono font-semibold" data-testid="text-total-debits">
                    {formatCurrency(totalDebits, entry.currencyCode, currencies)}
                  </TableCell>
                  <TableCell className="text-right font-mono font-semibold" data-testid="text-total-credits">
                    {formatCurrency(totalCredits, entry.currencyCode, currencies)}
                  </TableCell>
                </TableRow>
                <TableRow>
                  <TableCell colSpan={5} className="text-center">
                    {isBalanced ? (
                      <div className="flex items-center justify-center gap-2 text-green-600 dark:text-green-400" data-testid="text-balanced">
                        <CheckCircle className="h-4 w-4" />
                        <span className="font-medium">Balanced</span>
                      </div>
                    ) : (
                      <div className="flex items-center justify-center gap-2 text-destructive" data-testid="text-unbalanced">
                        <XCircle className="h-4 w-4" />
                        <span className="font-medium">
                          Unbalanced (Difference: {formatCurrency(Math.abs(totalDebits - totalCredits), entry.currencyCode, currencies)})
                        </span>
                      </div>
                    )}
                  </TableCell>
                </TableRow>
              </TableFooter>
            </Table>
          )}
        </CardContent>
      </Card>

      {/* Audit Trail Timeline */}
      {auditTrail.length > 0 && (
        <Card data-testid="card-audit-trail">
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <Clock className="h-5 w-5" />
              Audit Trail
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="space-y-6">
              {auditTrail.map((event, index) => (
                <div key={index} className="flex gap-4" data-testid={`audit-event-${index}`}>
                  <div className="flex flex-col items-center">
                    <div className="rounded-full bg-primary p-2">
                      {event.action.toLowerCase().includes('approve') ? (
                        <Check className="h-4 w-4 text-primary-foreground" />
                      ) : event.action.toLowerCase().includes('reject') ? (
                        <X className="h-4 w-4 text-primary-foreground" />
                      ) : (
                        <User className="h-4 w-4 text-primary-foreground" />
                      )}
                    </div>
                    {index < auditTrail.length - 1 && (
                      <div className="h-full w-0.5 bg-border mt-2 flex-1" />
                    )}
                  </div>
                  <div className="flex-1 pb-6">
                    <p className="font-medium" data-testid={`audit-action-${index}`}>
                      {event.action}
                    </p>
                    <p className="text-sm text-muted-foreground" data-testid={`audit-user-${index}`}>
                      {getUserName(event.user)} • {formatDateTime(event.timestamp)}
                    </p>
                    {event.comments && (
                      <p className="text-sm mt-1" data-testid={`audit-comments-${index}`}>
                        {event.comments}
                      </p>
                    )}
                  </div>
                </div>
              ))}
            </div>
          </CardContent>
        </Card>
      )}

      {/* Notes Section */}
      {entry.notes && (
        <Card data-testid="card-notes">
          <CardHeader>
            <CardTitle>Notes</CardTitle>
          </CardHeader>
          <CardContent>
            <p className="text-sm whitespace-pre-wrap" data-testid="text-notes">{entry.notes}</p>
          </CardContent>
        </Card>
      )}

      {/* Delete Confirmation Dialog */}
      <AlertDialog open={showDeleteDialog} onOpenChange={setShowDeleteDialog}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>Delete Journal Entry</AlertDialogTitle>
            <AlertDialogDescription>
              Are you sure you want to delete this journal entry? This action cannot be undone.
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel data-testid="button-cancel-delete">Cancel</AlertDialogCancel>
            <AlertDialogAction
              onClick={handleDelete}
              className="bg-destructive text-destructive-foreground hover:bg-destructive/90"
              data-testid="button-confirm-delete"
            >
              Delete
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>

      {/* Approve Dialog */}
      <Dialog open={showApproveDialog} onOpenChange={setShowApproveDialog}>
        <DialogContent data-testid="dialog-approve">
          <DialogHeader>
            <DialogTitle>Approve Journal Entry</DialogTitle>
            <DialogDescription>
              You are approving this journal entry at Step {approvalRequest?.currentStep}. 
              You can optionally add comments to explain your approval decision.
            </DialogDescription>
          </DialogHeader>
          <div className="space-y-4 py-4">
            <div className="space-y-2">
              <Label htmlFor="approve-comments">Comments (Optional)</Label>
              <Textarea
                id="approve-comments"
                placeholder="Add any comments about your approval decision..."
                value={approveComments}
                onChange={(e) => setApproveComments(e.target.value)}
                rows={4}
                data-testid="textarea-approve-comments"
              />
            </div>
          </div>
          <DialogFooter>
            <Button
              variant="outline"
              onClick={() => {
                setShowApproveDialog(false);
                setApproveComments("");
              }}
              disabled={approveMutation.isPending}
              data-testid="button-cancel-approve"
            >
              Cancel
            </Button>
            <Button
              onClick={handleApprove}
              disabled={approveMutation.isPending}
              data-testid="button-confirm-approve"
            >
              {approveMutation.isPending ? (
                <>Processing...</>
              ) : (
                <>
                  <CheckCircle className="mr-2 h-4 w-4" />
                  Approve
                </>
              )}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Reject Dialog */}
      <Dialog open={showRejectDialog} onOpenChange={setShowRejectDialog}>
        <DialogContent data-testid="dialog-reject">
          <DialogHeader>
            <DialogTitle>Reject Journal Entry</DialogTitle>
            <DialogDescription>
              You are rejecting this journal entry. Please provide a reason for the rejection.
            </DialogDescription>
          </DialogHeader>
          <div className="space-y-4 py-4">
            <div className="space-y-2">
              <Label htmlFor="reject-reason">
                Rejection Reason <span className="text-destructive">*</span>
              </Label>
              <Textarea
                id="reject-reason"
                placeholder="Explain why you are rejecting this entry..."
                value={rejectReason}
                onChange={(e) => setRejectReason(e.target.value)}
                rows={4}
                required
                data-testid="textarea-reject-reason"
              />
              <p className="text-xs text-muted-foreground">
                A rejection reason is required.
              </p>
            </div>
          </div>
          <DialogFooter>
            <Button
              variant="outline"
              onClick={() => {
                setShowRejectDialog(false);
                setRejectReason("");
              }}
              disabled={rejectMutation.isPending}
              data-testid="button-cancel-reject"
            >
              Cancel
            </Button>
            <Button
              variant="destructive"
              onClick={handleReject}
              disabled={rejectMutation.isPending || !rejectReason.trim()}
              data-testid="button-confirm-reject"
            >
              {rejectMutation.isPending ? (
                <>Processing...</>
              ) : (
                <>
                  <XCircle className="mr-2 h-4 w-4" />
                  Reject
                </>
              )}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
}
